### ISSUE TITLE
AWS bucket no longer exists

### ISSUE THREAD

**Issue by abelder1** [eddiepease/company2vec#12]
I'm running into an error with the setup file I believe because the AWX bucket no longer exists:
"An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist"
Can you check the bucket, or alternatively suggest another way to access the data files please? Any help appreciated!

**Comment by cassinaooo** [comment]
Hey, @abelder1. The files missing are easy to find on the web.

They are the `glove.6B.50d.txt` (https://www.kaggle.com/datasets/watts2/glove6b50dtxt) and `word_dictionary.json` (https://github.com/dwyl/english-words/blob/master/words_dictionary.json).

Putting both into `./data/` should do the trick.

**Comment by abelder1** [comment]
Thank you!
